# Generated by Django 5.2.8 on 2025-11-08 20:15

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_credits_task'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.UserManager()),
            ],
        ),
    ]
